permalink: /:title.html
highlighter: rouge
var:
  rss_path: /atom.xml

production_url: "http://statico.github.io"
title: "Ian Langworth's Things of Variable Interest"

author:
  name: Ian Langworth
  github: statico
  twitter: statico
