permalink: /:title.html
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"
var:
  rss_path: /atom.xml

title: "Ian Langworth's Things of Variable Interest"
production_url: "https://statico.github.io"
url: "https://statico.github.io"
old_url: "http://statico.github.io" # disqus migration crap

author:
  name: Ian Langworth
  github: statico
  twitter: statico
