permalink: /:title.html
auto: true
pygments: true
var:
  rss_path: /atom.xml

production_url: "http://statico.github.com"
title: "Ian Langworth's Things of Variable Interest"

author:
  name: Ian Langworth
  github: statico
  twitter: statico

exclude: .rbenv-version
